-- MySQL Script generated by MySQL Workbench
-- Mon May  8 15:20:20 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema system_testing_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema system_testing_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `system_testing_db` DEFAULT CHARACTER SET utf8 ;
USE `system_testing_db` ;

-- -----------------------------------------------------
-- Table `system_testing_db`.`tbl_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `system_testing_db`.`tbl_users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `role` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `system_testing_db`.`tbl_teachers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `system_testing_db`.`tbl_teachers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fio` VARCHAR(45) NOT NULL,
  `tbl_users_id` INT NOT NULL,
  PRIMARY KEY (`id`, `tbl_users_id`),
  INDEX `fk_tbl_teachers_tbl_users1_idx` (`tbl_users_id` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_teachers_tbl_users1`
    FOREIGN KEY (`tbl_users_id`)
    REFERENCES `system_testing_db`.`tbl_users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `system_testing_db`.`tbl_groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `system_testing_db`.`tbl_groups` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `number` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `system_testing_db`.`tbl_students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `system_testing_db`.`tbl_students` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fio` VARCHAR(45) NOT NULL,
  `tbl_users_id` INT NOT NULL,
  `tbl_groups_id` INT NOT NULL,
  PRIMARY KEY (`id`, `tbl_users_id`, `tbl_groups_id`),
  INDEX `fk_tbl_students_tbl_users1_idx` (`tbl_users_id` ASC) VISIBLE,
  INDEX `fk_tbl_students_tbl_groups1_idx` (`tbl_groups_id` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_students_tbl_users1`
    FOREIGN KEY (`tbl_users_id`)
    REFERENCES `system_testing_db`.`tbl_users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_students_tbl_groups1`
    FOREIGN KEY (`tbl_groups_id`)
    REFERENCES `system_testing_db`.`tbl_groups` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `system_testing_db`.`tbs_disciplines`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `system_testing_db`.`tbs_disciplines` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `system_testing_db`.`tbl_testes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `system_testing_db`.`tbl_testes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `tbs_disciplines_id` INT NOT NULL,
  PRIMARY KEY (`id`, `tbs_disciplines_id`),
  INDEX `fk_tbl_testes_tbs_disciplines1_idx` (`tbs_disciplines_id` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_testes_tbs_disciplines1`
    FOREIGN KEY (`tbs_disciplines_id`)
    REFERENCES `system_testing_db`.`tbs_disciplines` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `system_testing_db`.`tbl_questions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `system_testing_db`.`tbl_questions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `tbl_testes_id` INT NOT NULL,
  PRIMARY KEY (`id`, `tbl_testes_id`),
  INDEX `fk_tbl_questions_tbl_testes1_idx` (`tbl_testes_id` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_questions_tbl_testes1`
    FOREIGN KEY (`tbl_testes_id`)
    REFERENCES `system_testing_db`.`tbl_testes` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `system_testing_db`.`tbl_answers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `system_testing_db`.`tbl_answers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `is_true` TINYINT NOT NULL DEFAULT 0,
  `tbl_questions_id` INT NOT NULL,
  PRIMARY KEY (`id`, `tbl_questions_id`),
  INDEX `fk_tbl_answers_tbl_questions1_idx` (`tbl_questions_id` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_answers_tbl_questions1`
    FOREIGN KEY (`tbl_questions_id`)
    REFERENCES `system_testing_db`.`tbl_questions` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `system_testing_db`.`tbl_assessments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `system_testing_db`.`tbl_assessments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `assessment` VARCHAR(45) NOT NULL,
  `tbl_students_id` INT NOT NULL,
  `tbl_testes_id` INT NOT NULL,
  PRIMARY KEY (`id`, `tbl_students_id`, `tbl_testes_id`),
  INDEX `fk_tbl_assessments_tbl_students1_idx` (`tbl_students_id` ASC) VISIBLE,
  INDEX `fk_tbl_assessments_tbl_testes1_idx` (`tbl_testes_id` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_assessments_tbl_students1`
    FOREIGN KEY (`tbl_students_id`)
    REFERENCES `system_testing_db`.`tbl_students` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_assessments_tbl_testes1`
    FOREIGN KEY (`tbl_testes_id`)
    REFERENCES `system_testing_db`.`tbl_testes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `system_testing_db`.`tbl_schedules`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `system_testing_db`.`tbl_schedules` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  `tbl_groups_id` INT NOT NULL,
  `tbl_testes_id` INT NOT NULL,
  PRIMARY KEY (`id`, `tbl_groups_id`, `tbl_testes_id`),
  INDEX `fk_tbl_schedules_tbl_groups1_idx` (`tbl_groups_id` ASC) VISIBLE,
  INDEX `fk_tbl_schedules_tbl_testes1_idx` (`tbl_testes_id` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_schedules_tbl_groups1`
    FOREIGN KEY (`tbl_groups_id`)
    REFERENCES `system_testing_db`.`tbl_groups` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_schedules_tbl_testes1`
    FOREIGN KEY (`tbl_testes_id`)
    REFERENCES `system_testing_db`.`tbl_testes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `system_testing_db`.`tbl_teachers_has_tbs_disciplines`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `system_testing_db`.`tbl_teachers_has_tbs_disciplines` (
  `tbl_teachers_id` INT NOT NULL,
  `tbs_disciplines_id` INT NOT NULL,
  PRIMARY KEY (`tbl_teachers_id`, `tbs_disciplines_id`),
  INDEX `fk_tbl_teachers_has_tbs_disciplines_tbs_disciplines1_idx` (`tbs_disciplines_id` ASC) VISIBLE,
  INDEX `fk_tbl_teachers_has_tbs_disciplines_tbl_teachers1_idx` (`tbl_teachers_id` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_teachers_has_tbs_disciplines_tbl_teachers1`
    FOREIGN KEY (`tbl_teachers_id`)
    REFERENCES `system_testing_db`.`tbl_teachers` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_tbl_teachers_has_tbs_disciplines_tbs_disciplines1`
    FOREIGN KEY (`tbs_disciplines_id`)
    REFERENCES `system_testing_db`.`tbs_disciplines` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
